### ISSUE TITLE
The mediator won't be loaded even if I install the library with cocoapods.

### ISSUE THREAD

**Issue by RyogaK** [united-adstir/AdStir-Integration-Guide-iOS#1]
Hi, the problem is as the title.

I can install the framework, but `libAdMobMediationAdapter-AdstirAds.a` won't be installed.
It seems the path is not made.

I think you should make podspec as the following.

``` podspec.rb
Pod::Spec.new do |s|
    s.source  = { :http => "https://example.com/path/to/AnySDK.zip", :flatten => true }
    s.source_files  = 'AnySDK/**/*.h'
    s.preserve_paths  = 'AnySDK/**/*.a'
    s.xcconfig  = { 'LIBRARY_SEARCH_PATHS' => '"$(PODS_ROOT)/AnySDK/**"' }
end
```

How is this?

**Comment by 0tarof** [comment]
Thank you for contacting us.

We didn't contain the library `libAdMobMediationAdapter-AdstirAds.a` because its only needed for using AdMob Mediation and depends on pods `Google-Mobile-Ads-SDK`.

..but, we maybe able to use subspec definition.
So we'll test the subspec definition and try to contain subspec in future release.

Regards,

**Comment by 0tarof** [comment]
@RyogaK 
Hi, we've updated podspec to support AdMob mediation adapter.

Now, you can use like this:

``` ruby
platform: ios, "6.0"
pod 'AdStir-Ads-SDK'
pod 'AdStir-Ads-SDK/AdMobMediationAdapter'
```

Thanks.
